"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _project_card from './project-card.bones.json'

registerBones({
  "project-card": _project_card,
})
